# Generated by Django 3.2.3 on 2021-05-19 00:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Certificate_type',
            new_name='certificate_type',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Faculty',
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ModelsApp.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.DateField(),
        ),
    ]
