# Generated by Django 3.2.3 on 2021-05-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0002_auto_20210518_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
    ]
